all: 
	ocamlbuild -use-ocamlfind fontmaker.native

clean:
	ocamlbuild -use-ocamlfind -clean

font:
	./fontmaker.byte -c "@#$\%^&*()_+-=<>|/!?\"'№:,.;{}[]qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNMйцукенгшщзхъёфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪЁФЫВАПРОЛДЖЭЯЧСМИТЬБЮ1234567890" -s 10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25 -o ~/projects/mobile-farm/Resources/fonts $(path) 
