BIN_FNAME = texcmprss
COMPILER = g++ -arch i386 -g -Wno-write-strings

all:
	$(COMPILER) -I../include -L../osx/lib main.cpp -lTextureConverter -lQCompressLib -lFreeImage -o $(BIN_FNAME)

clean:
	rm -f *.o $(BIN_FNAME)